[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build:client",
  "npm run build:server"
]

[start]
cmd = "npm run db:migrate && npm start" 